### ISSUE TITLE
librosa.load()函数在多线程下无法使用？

### ISSUE THREAD

**Issue by longglecc** [lissettecarlr/kuon#5]
python kuon.py 在使用中，每一次跑到语音转写文字时，在加载音频文件的时候，线程就卡住了，我追踪到librosa.load()函数，没有抛出任何报错信息。但是运行python test_speech_to_text.py时，就没有任何问题，可以正常转写。

![image](https://github.com/lissettecarlr/kuon/assets/33145006/37c8d223-5026-443b-b2e0-aa8d4360c424)
![image](https://github.com/lissettecarlr/kuon/assets/33145006/4652fd31-2f44-46fc-b97f-e98b982eb2df)

**Comment by lissettecarlr** [comment]
![123](https://github.com/lissettecarlr/kuon/assets/16299917/b143e733-ec45-4bae-a072-771a7163cb57)
最近一直很多其他事儿，没继续更新。刚克隆下来试了试，是可以的，就是很慢。  之前也一直头疼这问题，模型在子线程，或者开的子进程中运行速度都变得特别慢，感觉是推理方式的问题。之前我是准备将所有推理就主线程里跑了，还没开工改- -|

**Comment by longglecc** [comment]
是因为pycharm的问题，导致线程卡死了。
